exclude: 'doc/conf.py'

repos:

- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.8.0'
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
    - id: ruff-format


- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.9.1
  hooks:
    - id: nbqa-black
      additional_dependencies: [black==20.8b1]
      args: [--line-length=120]
    - id: nbqa-isort
      additional_dependencies: [isort==5.7.0]
      args: [--profile=black, --line-length=120]
