exclude: 'doc/conf.py'

repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.25.1
    hooks:
    -   id: pyupgrade
        # for now don't force to change from %-operator to {}
        args: [--keep-percent-format, --py36-plus]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
    -   id: fix-encoding-pragma
        args: [--remove]

-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black

#-   repo: https://github.com/PyCQA/isort/
#    rev: 5.8.0
#    hooks:
#    -   id: isort

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.1.0
  hooks:
    - id: nbqa-black
      additional_dependencies: [black==20.8b1]
      args: [--nbqa-mutate, --line-length=120]
    - id: nbqa-isort
      additional_dependencies: [isort==5.7.0]
      args: [--profile=black, --nbqa-mutate, --line-length=120]
