exclude: 'doc/conf.py'

repos:

-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black


- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.3.1
  hooks:
    - id: nbqa-black
      additional_dependencies: [black==20.8b1]
      args: [--line-length=120]
    - id: nbqa-isort
      additional_dependencies: [isort==5.7.0]
      args: [--profile=black, --line-length=120]
