language: python
cache: pip

matrix:
  include:
  - name: "Python 3.11"
    python: "3.11"
    dist: ubuntu-latest
  - name: "Python 3.12"
    python: "3.12"
    dist: ubuntu-latest

before_install:
  - sudo apt-get install -y swig


install:
    - ls
    - which swig
    - swig -version
    - pip install OApackage

    - python setup.py install
    - python -c "import oapackage; print(oapackage.compile_information())"
    - pip install pytest mypy

script:
    - pytest
    - mypy oaresearch --ignore-missing-imports

    # run scripts
    - python scripts/articles/article-dof-example-appendix.py > /dev/null
    - python scripts/articles/conference_designs_running_times.py
