language: python
cache: pip

matrix:
  include:
  - name: "Python 3.7"
    python: "3.7"
    dist: bionic
  - name: "Python 3.6"
    python: "3.6"
    
before_install:
  - sudo apt-get install -y swig3.0
  
       
install:
    - ls
    - which swig3.0
    - pip install OApackage
    #- pip install git+git://github.com/eendebakpt/oapackage.git@02338cc9b917f7a3bcfabdcb01eb4d9c1a8cf49a
    #- pip install OApackage
    
    - python setup.py install
    - python -c "import oapackage; print(oapackage.compile_information())"
    - pip install pytest mypy

script: 
    - pytest
    - mypy oaresearch --ignore-missing-imports

# run scripts

    - python scripts/articles/article-dof-example-appendix.py
    
