language: python
cache: pip

matrix:
  include:
  - name: "Python 3.9"
    python: "3.9"
    dist: bionic
  - name: "Python 3.8"
    python: "3.8"
    dist: bionic
  - name: "Python 3.7"
    python: "3.7"
    dist: bionic

before_install:
  - sudo apt-get install -y swig3.0


install:
    - ls
    - which swig3.0
    - pip install OApackage

    - python setup.py install
    - python -c "import oapackage; print(oapackage.compile_information())"
    - pip install pytest mypy

script:
    - pytest
    - mypy oaresearch --ignore-missing-imports

    # run scripts
    - python scripts/articles/article-dof-example-appendix.py > /dev/null
    - python scripts/articles/conference_designs_running_times.py
