language: python
cache: pip

matrix:
  include:
  - name: "Python 3.6"
    python: "3.6"
  - name: "Python 2.7"
    python: "2.7"

addons:
  apt_packages:
    - swig
        
install:
    - python setup.py develop
    - pip install pytest

script: 
    - pytest
    